image_root: '/home/sooyoung/ps/CUHK-PEDES/imgs'
train_files: ['/home/sooyoung/ps/CUHK-PEDES/processed_data/train.json']
val_files: '/home/sooyoung/ps/CUHK-PEDES/processed_data/val.json'
test_files: '/home/sooyoung/ps/CUHK-PEDES/processed_data/test.json'
train_image_root: '/home/sooyoung/ps/CUHK-PEDES/imgs'
val_image_root: '/home/sooyoung/ps/CUHK-PEDES/imgs'
test_image_root: '/home/sooyoung/ps/CUHK-PEDES/imgs'
dataset: 'cuhk'

# set pretrained as a file path or an url
#pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_retrieval_flickr.pth'
#pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_retrieval_coco.pth'
pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large_retrieval_coco.pth'
#pretrained: '/home/sooyoung/ps/BLIP/output/Pretrain_CUHK_vitB_img224/checkpoint_19.pth'
#pretrained: '/home/sooyoung/ps/BLIP/output/Pretrain_CUHK_vitB_img224_from_weight/checkpoint_02.pth'
# size of vit model; base or large

# vit: 'base'
# batch_size_train: 24
# batch_size_test: 32
# vit_grad_ckpt: True
# vit_ckpt_layer: 4
# init_lr: 1e-5

vit: 'large'
batch_size_train: 8
batch_size_test: 24
vit_grad_ckpt: True
vit_ckpt_layer: 12
init_lr: 1e-5 # 5e-6

max_words: 30

image_res: 384
# image_res: 384
queue_size: 57600
alpha: 0.4
# k_test: 128
# negative_all_rank: False
k_test: 256
negative_all_rank: True

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 30

